# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4f3b49e50210818e1f8a6844b92c459f44e3fae304d60ef9009453cba0183dd659c738fac641c4522132460d64187c5037ded4c8f51a056caa61b4fc57697115

test:
  secret_key_base: b5613664496a8de9bcc3f7c5a08862f3b0662b48fb5538e9797b544f1f3d155a41accb41774596fb96281f7f2ef1c41acabfd89c8ea0baeb90e3334f8650560b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
